### ISSUE TITLE
Different ways to add data

### ISSUE THREAD

**Issue by ElizabethFernandes** [ubc-library-rc/gis-intro-qgis#12]
At: https://ubc-library-rc.github.io/gis-intro-qgis/content/add-data.html

Hey, Evan, I noticed there are two different way to add data. As I didn't know which one would be your favorite, I added both and then you can decide which one should be kept.

On the other hand, given that probably many people will be taking this workshop by themselves, I thought that it would be good to have both options showing :)

**Comment by lilydemet** [comment]
both options added
