### ISSUE TITLE
Color change on trees

### ISSUE THREAD

**Issue by ElizabethFernandes** [ubc-library-rc/gis-intro-qgis#14]
At: https://ubc-library-rc.github.io/gis-intro-qgis/content/select-attributes.html#create-a-new-layer-from-your-douglas-fir-tree-selection

The color representation changed although I didn't change the color scheme, so... I hope I didn't do anything wrong?

**Comment by lilydemet** [comment]
The different colored dots are the trees whose common name is douglas fir. when you unselect, the color should return to your chosen symbology.
