### ISSUE TITLE
Uncertain page location 

### ISSUE THREAD

**Issue by lilydemet** [ubc-library-rc/gis-intro-qgis#19]
@ect123 
I deleted *under construction* from README.md but it still has the notice on this page:https://ubc-library-rc.github.io/gis-intro-qgis/content/

unsure where it's located so as to update it... 
looks like it's in /content, but I don't know what kind of file it is and it doesn't show up when I go $ ls

**Comment by ect123** [comment]
@lilydemet Good eye! That's a hidden page and isn't linked from any of the other pages in the workshop, so most folks probably wont see it. But, it looks like there's README file in that directory which is being displayed by default at that endpoint. [https://github.com/ubc-library-rc/gis-intro-qgis/tree/master/content](https://github.com/ubc-library-rc/gis-intro-qgis/tree/master/content).

I think it's probably ok to either delete the README (which will give that page a 404 error) or leave it blank (which will just make it a blank page).
