### ISSUE TITLE
QGIS version 3.10 or 3.4?

### ISSUE THREAD

**Issue by ElizabethFernandes** [ubc-library-rc/gis-intro-qgis#2]
The main page says this workshop explores QGIS 3.10 (https://ubc-library-rc.github.io/gis-intro-qgis/), but at https://ubc-library-rc.github.io/gis-intro-qgis/content/qgis-overview.html it is said that we will use version 3.4.

From the "ups and downs" I'd assume we would work with the "Long term release" (version 3.4). Maybe it could be explained in the beginning that although there is a "latest version", it is usually buggy, which is why we usually choose to work with the 3.4.  I just think it is important to be consistent: if we work with 3.4, maybe change the introduction to say we will use 3.4?

**Comment by ect123** [comment]
This is probably a larger issue that will involve changes throughout the site, so we can look for other instances of miss-matched QGIS versions. The current long-term-release is v3.10 [as seen on the QGIS download page](https://qgis.org/en/site/forusers/download.html).

Let's first focus on correcting the version statements in-text on this page in response to this specific issue. Then if mismatched versions affect other things like screenshots or button placements then we can add those as separate issues.

**Comment by ElizabethFernandes** [comment]
I have updated the text to 3.10, but, screenshots will probably have to be updated.
